[package]
name = "aletheia_protocol"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "aletheia_protocol"

[dependencies]
anchor-lang = "0.29.0"
mpl-bubblegum = "1.4.0"
mpl-token-metadata = "4.1.2"
spl-account-compression = { version = "0.3.0", features = ["no-entrypoint"] }
spl-noop = { version = "0.2.0", features = ["no-entrypoint"] }
ark-bn254 = { version = "0.4.0", features = ["curve"] }
ark-groth16 = { version = "0.4.0", default-features = false, features = ["r1cs"] }
ark-snark = "0.4.0"
ark-serialize = "0.4.2"

[profile.release]
overflow-checks = true

[features]
default = []
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = []
cpi = ["no-entrypoint"]
anchor-debug = []
custom-heap = []
custom-panic = []